import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

def send_mood_email(email, app_password, user_name, mood, quote, recipes, places, suggestions):
    try:
        # Zoho SMTP server details
        smtp_server = "smtp.zoho.com"
        smtp_port = 587

        # Email setup
        msg = MIMEMultipart()
        msg['From'] = email
        msg['To'] = email  # Sending to self
        msg['Subject'] = f"🧠 Mood Report for {user_name} - {mood.upper()}"

        # Email body
        body = f"""
        <h2>🧠 Hello {user_name}!</h2>
        <p><b>Your Predicted Mood:</b> {mood.upper()}</p>
        <p><b>💡 Motivational Quote:</b> {quote}</p>
        <p><b>🥗 Suggested Recipes:</b> {', '.join(recipes)}</p>
        <p><b>📍 Places to Visit:</b> {', '.join(places)}</p>
        <p><b>🎯 AI Suggestions:</b> {', '.join(suggestions)}</p>
        <hr>
        <p style="color:gray;">🔐 This message was auto-generated by the Emoji Mood App.</p>
        """

        msg.attach(MIMEText(body, 'html'))

        # Connect and send
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(email, app_password)
        server.send_message(msg)
        server.quit()

        print("[✅] Email successfully sent to your inbox.")

    except Exception as e:
        print(f"[⚠️] Email sending failed inside mailer: {e}")
